steps:
  # Step to build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/cobalt-ship-434308-h6/trial1/trial:1.0', '.']

  # Step to push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/cobalt-ship-434308-h6/trial1/trial:1.0']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'trial1'
      - '--image'
      - 'gcr.io/cobalt-ship-434308-h6/trial1/trial:1.0'
      - '--region'
      - 'asia-east1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'


images:
  - 'gcr.io/cobalt-ship-434308-h6/trial1/trial:1.0'

options:
  logging: CLOUD_LOGGING_ONLY
